#!/bin/sh
echo "NEXT_PUBLIC_EVOLUTION_URL=$NEXT_PUBLIC_EVOLUTION_URL" > .env
echo "NEXT_PUBLIC_EVOLUTION_API=$NEXT_PUBLIC_EVOLUTION_API" >> .env
echo "NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL" >> .env
echo "NEXT_PUBLIC_AUTH_USERNAME=$AUTH_USERNAME" >> .env
echo "NEXT_PUBLIC_AUTH_PASSWORD=$AUTH_PASSWORD" >> .env
echo "AUTH_SECRET_KEY=$AUTH_SECRET_KEY" >> .env
echo "NEXT_PUBLIC_CHATWOOT_INTEGRATION=$NEXT_PUBLIC_CHATWOOT_INTEGRATION" >> .env
echo "NEXT_PUBLIC_CHATWOOT_DOMAIN=$NEXT_PUBLIC_CHATWOOT_DOMAIN" >> .env
echo "NEXT_PUBLIC_CHATWOOT_ACCOUNT_ID=$NEXT_PUBLIC_CHATWOOT_ACCOUNT_ID" >> .env
echo "NEXT_PUBLIC_CHATWOOT_TOKEN=$NEXT_PUBLIC_CHATWOOT_TOKEN" >> .env
echo "NEXT_PUBLIC_CHATWOOT_DATABASE_CONNECTION_URI=$NEXT_PUBLIC_CHATWOOT_DATABASE_CONNECTION_URI" >> .env
echo "NEXT_PUBLIC_AUTO_FILL_DDI=${NEXT_PUBLIC_AUTO_FILL_DDI:-true}" >> .env
echo "NEXT_PUBLIC_DEFAULT_LOCATION=${NEXT_PUBLIC_DEFAULT_LOCATION:-BR}" >> .env
npm run build
npm start
